// FileManager action types
export const FILE_MANAGER_OPEN_DIALOG = 'FILE_MANAGER_OPEN_DIALOG';
export const FILE_MANAGER_OPEN_DIALOG_SUCCESS = 'FILE_MANAGER_OPEN_DIALOG_SUCCESS';
export const FILE_MANAGER_OPEN_DIALOG_FAILURE = 'FILE_MANAGER_OPEN_DIALOG_FAILURE';

export const OPEN_FILE_MANAGER = 'OPEN_FILE_MANAGER';
export const OPEN_FILE_MANAGER_SUCCESS = 'OPEN_FILE_MANAGER_SUCCESS';
export const OPEN_FILE_MANAGER_FAILURE = 'OPEN_FILE_MANAGER_FAILURE';
