"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL';
exports.CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
exports.CLEAR_ALL_NOTIFICATIONS = 'CLEAR_ALL_NOTIFICATIONS';
exports.TOGGLE_LOADER_PANEL = 'TOGGLE_LOADER_PANEL';
exports.TOGGLE_SETTINGS_PANEL = 'TOGGLE_SETTINGS_PANEL';
exports.TOGGLE_SEARCH_PANEL = 'TOGGLE_SEARCH_PANEL';
exports.ADD_APP_ITEM = 'ADD_APP_ITEM';
exports.SWITCH_DAPP = 'SWITCH_DAPP';
exports.TOGGLE_HOME = 'TOGGLE_HOME';
exports.TOGGLE_APP_HOME = 'TOGGLE_APP_HOME';
exports.SET_TRAY_COUNTER = 'SET_TRAY_COUNTER';
exports.SET_TRAY_PROGRESS = 'SET_TRAY_PROGRESS';
exports.REMOVE_TRAY_ITEM = 'REMOVE_TRAY_ITEM';
exports.APPS_FEED_RESIZE = 'APPS_FEED_RESIZE';
// Dapp communication protocol
exports.INTENT_OPEN_CHANNELS = 'INTENT_OPEN_CHANNELS';
exports.OPEN_CHANNEL = 'OPEN_CHANNEL';
exports.BIND_OPEN_CHANNELS = 'BIND_OPEN_CHANNELS';
exports.BIND_OPEN_CHANNELS_DONE = 'BIND_OPEN_CHANNELS_DONE';
exports.OPEN_CHANNEL_SUCCESS = 'OPEN_CHANNEL_SUCCESS';
exports.OPEN_CHANNEL_FAILURE = 'OPEN_CHANNEL_FAILURE';
exports.TOGGLE_STATUS_BAR_PANEL = 'TOGGLE_STATUS_BAR_PANEL';
exports.TOGGLE_PEERS_BAR_PANEL = 'TOGGLE_PEERS_BAR_PANEL';
// Component-channel resolver
exports.INTENT_CHANNEL_DATA_PASS = 'INTENT_CHANNEL_DATA_PASS';
exports.ACCEPT_CHANNEL_DATA_PASS = 'ACCEPT_CHANNEL_DATA_PASS';
// Permission manager
exports.TOGGLE_PERMISSION = 'TOGGLE_PERMISSION';
exports.GRANT_PERMISSIONS = 'GRANT_PERMISSIONS';
exports.CLOSE_MANAGER = 'CLOSE_MANAGER';
exports.LOAD_PERMISSIONS = 'LOAD_PERMISSIONS';
// FileManager action types
exports.FILE_MANAGER_OPEN_DIALOG = 'FILE_MANAGER_OPEN_DIALOG';
exports.FILE_MANAGER_OPEN_DIALOG_SUCCESS = 'FILE_MANAGER_OPEN_DIALOG_SUCCESS';
exports.FILE_MANAGER_OPEN_DIALOG_FAILURE = 'FILE_MANAGER_OPEN_DIALOG_FAILURE';
exports.OPEN_FILE_MANAGER = 'OPEN_FILE_MANAGER';
exports.OPEN_FILE_MANAGER_SUCCESS = 'OPEN_FILE_MANAGER_SUCCESS';
exports.OPEN_FILE_MANAGER_FAILURE = 'OPEN_FILE_MANAGER_FAILURE';
exports.SHOW_FILE_ENTRIES = 'SHOW_FILE_ENTRIES';
// IPFS Storage
exports.IPFS_STORAGE_UPLOAD_FILES = 'IPFS_STORAGE_UPLOAD_FILES';
exports.IPFS_STORAGE_UPLOAD_FILES_SUCCESS = 'IPFS_STORAGE_UPLOAD_FILES_SUCCESS';
exports.IPFS_STORAGE_UPLOAD_FILES_FAILURE = 'IPFS_STORAGE_UPLOAD_FILES_FAILURE';
