// Dapp communication protocol
const INTENT_OPEN_CHANNELS = 'INTENT_OPEN_CHANNELS';
const OPEN_CHANNEL = 'OPEN_CHANNEL';
const OPEN_CHANNEL_SUCCESS = 'OPEN_CHANNEL_SUCCESS';
const OPEN_CHANNEL_FAILURE = 'OPEN_CHANNEL_FAILURE';
const BIND_OPEN_CHANNELS = 'BIND_OPEN_CHANNELS';
const BIND_OPEN_CHANNELS_DONE = 'BIND_OPEN_CHANNELS_DONE';

// Events API protocol
const INIT_EVENT_SUBSCRIPTION = 'INIT_EVENT_SUBSCRIPTION';
const EVENT_TRIGGERED = 'EVENT_TRIGGERED';
const EVENT_RECEIVED = 'EVENT_RECEIVED';
 
// Component-channel resolver
const INTENT_CHANNEL_DATA_PASS = 'INTENT_CHANNEL_DATA_PASS';
const ACCEPT_CHANNEL_DATA_PASS = 'ACCEPT_CHANNEL_DATA_PASS';
 
///////

const SWITCH_DAPP = 'SWITCH_DAPP';
const SEND_PING_MESSAGE = 'SEND_PING_MESSAGE';

////////

const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
const START_COUNTDOWN = 'START_COUNTDOWN';
const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
const CANCEL_INCREMENT_ASYNC = 'CANCEL_INCREMENT_ASYNC';
const COUNTDOWN_TERMINATED = 'COUNTDOWN_TERMINATED';
