export const DAPP_SET_FOCUS = 'DAPP_SET_FOCUS';
export const DAPP_RESET_FOCUS = 'DAPP_RESET_FOCUS';
export const DAPP_CONTENT_LOADED = 'DAPP_CONTENT_LOADED';
export const DAPP_ACTION_OPEN_LINK = 'DAPP_ACTION_OPEN_LINK';
export const DAPP_ACTION_OPEN_LINK_SUCCESS = 'DAPP_ACTION_OPEN_LINK_SUCCESS';

export const SET_MAIN_TRAY_COUNTER = 'SET_MAIN_TRAY_COUNTER';
export const DAPP_SET_TRAY_COUNTER = 'DAPP_SET_TRAY_COUNTER';
