export const SELECT_ROOM = 'SELECT_ROOM';
export const DESELECT_ROOM = 'DESELECT_ROOM';

// Forms
export const FORM_CREATE_ROOM = 'FORM_CREATE_ROOM';
export const FORM_CHAT_SUBMIT_MESSAGE = 'FORM_CHAT_SUBMIT_MESSAGE';
export const FORM_CHAT_ROOMS_SEARCH = 'FORM_CHAT_ROOMS_SEARCH';

export const FIELD_FORM_CHAT_ROOMS_SEARCH_STRING = 'FIELD_FORM_CHAT_ROOMS_SEARCH_STRING';

// Events
export const EVENT_OPEN_LINK = 'openLink';
export const EVENT_SET_TRAY_COUNTER = 'setTrayCounter';
export const EVENT_DAPP_SET_FOCUS = 'dappSetFocus';
export const EVENT_DAPP_RESET_FOCUS = 'dappResetFocus';

// Messages reducer
export const MESSAGES_ADD_ROOM_MESSAGE = 'MESSAGES_ADD_ROOM_MESSAGE';
export const MESSAGES_REMOVE_ROOM_MESSAGES = 'MESSAGES_REMOVE_ROOM_MESSAGES';
export const ROOM_SET_UNREAD_MESSAGES = 'ROOM_SET_UNREAD_MESSAGES';

// Rooms
export const ROOMS_ADD = 'ROOMS_ADD';
export const ROOMS_REMOVE = 'ROOMS_REMOVE';
export const ROOMS_SET_FILTERED_ROOMS_LIST = 'ROOMS_SET_FILTERED_ROOMS_LIST';
export const ROOMS_RESET_FILTERED_ROOMS_LIST = 'ROOMS_RESET_FILTERED_ROOMS_LIST';

// Main
export const MAIN_SET_DAPP_FOCUSED = 'MAIN_SET_DAPP_FOCUSED';
export const MAIN_RESET_DAPP_FOCUSED = 'MAIN_RESET_DAPP_FOCUSED';
