export const SELECT_ROOM = 'SELECT_ROOM';
export const DESELECT_ROOM = 'DESELECT_ROOM';

// Forms
export const FORM_CREATE_ROOM = 'FORM_CREATE_ROOM';
export const FORM_CHAT_SUBMIT_MESSAGE = 'FORM_CHAT_SUBMIT_MESSAGE';
export const FORM_CHAT_PAGE_ROOMS_SEARCH = 'FORM_CHAT_PAGE_ROOMS_SEARCH';

export const INIT_APP = 'INIT_APP';

// Events
export const EVENT_OPEN_LINK = 'openLink';

// Messages reducer
export const MESSAGES_ADD_ROOM_MESSAGE = 'MESSAGES_ADD_ROOM_MESSAGE';
export const MESSAGES_REMOVE_ROOM_MESSAGES = 'MESSAGES_REMOVE_ROOM_MESSAGES';

// Rooms
export const ROOMS_ADD = 'ROOMS_ADD';
export const ROOMS_REMOVE = 'ROOMS_REMOVE';
export const ROOMS_SET_FILTERED_ROOMS_LIST = 'ROOMS_SET_FILTERED_ROOMS_LIST';
export const ROOMS_RESET_FILTERED_ROOMS_LIST = 'ROOMS_RESET_FILTERED_ROOMS_LIST';
