// Dapp communication protocol
export const INTENT_OPEN_CHANNELS = 'INTENT_OPEN_CHANNELS';
export const OPEN_CHANNEL = 'OPEN_CHANNEL';
export const OPEN_CHANNEL_SUCCESS = 'OPEN_CHANNEL_SUCCESS';
export const BIND_OPEN_CHANNELS_DONE = 'BIND_OPEN_CHANNELS_DONE';

// Events API protocol
export const INIT_EVENT_SUBSCRIPTION = 'INIT_EVENT_SUBSCRIPTION';
export const EVENT_TRIGGERED = 'EVENT_TRIGGERED';
export const EVENT_RECEIVED = 'EVENT_RECEIVED';

// Component-channel resolver
export const INTENT_CHANNEL_DATA_PASS = 'INTENT_CHANNEL_DATA_PASS';
export const ACCEPT_CHANNEL_DATA_PASS = 'ACCEPT_CHANNEL_DATA_PASS';

export const SHOW_FILE_ENTRIES = 'SHOW_FILE_ENTRIES';

export const NETWORK_GET_BLOCK = 'NETWORK_GET_BLOCK';
export const NETWORK_GET_BLOCK_SUCCESS = 'NETWORK_GET_BLOCK_SUCCESS';
export const NETWORK_GET_BLOCK_FAILURE = 'NETWORK_GET_BLOCK_FAILURE';

export const NETWORK_GET_WITNESS = 'NETWORK_GET_WITNESS';
export const NETWORK_GET_WITNESS_SUCCESS = 'NETWORK_GET_WITNESS_SUCCESS';
export const NETWORK_GET_WITNESS_FAILURE = 'NETWORK_GET_WITNESS_FAILURE';

export const NETWORK_SUBSCRIBE = 'NETWORK_SUBSCRIBE';
export const NETWORK_SUBSCRIBE_SUCCESS = 'NETWORK_SUBSCRIBE_SUCCESS';
export const NETWORK_SUBSCRIBE_FAILURE = 'NETWORK_SUBSCRIBE_FAILURE';
export const NETWORK_UNSUBSCRIBE = 'NETWORK_UNSUBSCRIBE';
export const NETWORK_UNSUBSCRIBE_SUCCESS = 'NETWORK_UNSUBSCRIBE_SUCCESS';
export const NETWORK_UNSUBSCRIBE_FAILURE = 'NETWORK_UNSUBSCRIBE_FAILURE';

export const NETWORK_BLOCK_CREATED = 'NETWORK_BLOCK_CREATED';

export const SHOW_BLOCK = 'SHOW_BLOCK';

export const LOGGER_WRITE = 'LOGGER_WRITE';
export const LOGGER_WRITE_SUCCESS = 'LOGGER_WRITE_SUCCESS';
export const LOGGER_WRITE_FAILURE = 'LOGGER_WRITE_FAILURE';

export const KEYCHAIN_CREATE = 'KEYCHAIN_CREATE';
export const KEYCHAIN_CREATE_SUCCESS = 'KEYCHAIN_CREATE_SUCCESS';
export const KEYCHAIN_CREATE_FAILURE = 'KEYCHAIN_CREATE_FAILURE';
export const KEYCHAIN_LIST = 'KEYCHAIN_LIST';
export const KEYCHAIN_LIST_SUCCESS = 'KEYCHAIN_LIST_SUCCESS';
export const KEYCHAIN_LIST_FAILURE = 'KEYCHAIN_LIST_FAILURE';
export const KEYCHAIN_SIGN = 'KEYCHAIN_SIGN';
export const KEYCHAIN_SIGN_SUCCESS = 'KEYCHAIN_SIGN_SUCCESS';
export const KEYCHAIN_SIGN_FAILURE = 'KEYCHAIN_SIGN_FAILURE';
export const KEYCHAIN_PUBLIC_KEY = 'KEYCHAIN_PUBLIC_KEY';
export const KEYCHAIN_PUBLIC_KEY_SUCCESS = 'KEYCHAIN_PUBLIC_KEY_SUCCESS';
export const KEYCHAIN_PUBLIC_KEY_FAILURE = 'KEYCHAIN_PUBLIC_KEY_FAILURE';

export const ETHEREUM_BUILD_TRANSACTION = 'ETHEREUM_BUILD_TRANSACTION';
export const ETHEREUM_BUILD_TRANSACTION_SUCCESS = 'ETHEREUM_BUILD_TRANSACTION_SUCCESS';
export const ETHEREUM_BUILD_TRANSACTION_FAILURE = 'ETHEREUM_BUILD_TRANSACTION_FAILURE';

export const ETHEREUM_PUBLISH_TRANSACTION = 'ETHEREUM_PUBLISH_TRANSACTION';
export const ETHEREUM_PUBLISH_TRANSACTION_SUCCESS = 'ETHEREUM_PUBLISH_TRANSACTION_SUCCESS';
export const ETHEREUM_PUBLISH_TRANSACTION_FAILURE = 'ETHEREUM_PUBLISH_TRANSACTION_FAILURE';

export const ETHEREUM_PUBLIC_TO_ADDRESS = 'ETHEREUM_PUBLIC_TO_ADDRESS';
export const ETHEREUM_PUBLIC_TO_ADDRESS_SUCCESS = 'ETHEREUM_PUBLIC_TO_ADDRESS_SUCCESS';
export const ETHEREUM_PUBLIC_TO_ADDRESS_FAILURE = 'ETHEREUM_PUBLIC_TO_ADDRESS_FAILURE';

export const KEYCHAIN_SHOW_RESULT = 'KEYCHAIN_SHOW_RESULT';

export const TOGGLE_APP_HOME_SUCCESS = 'TOGGLE_APP_HOME_SUCCESS';
export const TOGGLE_HOME = 'TOGGLE_HOME';

export const NOTIFICATIONS_SHOW_NOTIFY = 'NOTIFICATIONS_SHOW_NOTIFY';
