"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Dapp communication protocol
exports.INTENT_OPEN_CHANNELS = 'INTENT_OPEN_CHANNELS';
exports.OPEN_CHANNEL = 'OPEN_CHANNEL';
exports.OPEN_CHANNEL_SUCCESS = 'OPEN_CHANNEL_SUCCESS';
exports.BIND_OPEN_CHANNELS_DONE = 'BIND_OPEN_CHANNELS_DONE';
// Events API protocol
exports.INIT_EVENT_SUBSCRIPTION = 'INIT_EVENT_SUBSCRIPTION';
exports.EVENT_TRIGGERED = 'EVENT_TRIGGERED';
exports.EVENT_RECEIVED = 'EVENT_RECEIVED';
// Component-channel resolver
exports.INTENT_CHANNEL_DATA_PASS = 'INTENT_CHANNEL_DATA_PASS';
exports.ACCEPT_CHANNEL_DATA_PASS = 'ACCEPT_CHANNEL_DATA_PASS';
exports.SHOW_FILE_ENTRIES = 'SHOW_FILE_ENTRIES';
exports.FILE_MANAGER_OPEN_DIALOG = 'FILE_MANAGER_OPEN_DIALOG';
exports.FILE_MANAGER_OPEN_DIALOG_SUCCESS = 'FILE_MANAGER_OPEN_DIALOG_SUCCESS';
exports.FILE_MANAGER_OPEN_DIALOG_FAILURE = 'FILE_MANAGER_OPEN_DIALOG_FAILURE';
exports.IPFS_STORAGE_UPLOAD_FILES = 'IPFS_STORAGE_UPLOAD_FILES';
exports.IPFS_STORAGE_UPLOAD_FILES_SUCCESS = 'IPFS_STORAGE_UPLOAD_FILES_SUCCESS';
exports.IPFS_STORAGE_UPLOAD_FILES_FAILURE = 'IPFS_STORAGE_UPLOAD_FILES_FAILURE';
