export const CLIENT_IPFS_STORAGE_UPLOAD_FILE = 'CLIENT_IPFS_STORAGE_UPLOAD_FILE';
export const CLIENT_IPFS_STORAGE_UPLOAD_FILE_SUCCESS = 'CLIENT_IPFS_STORAGE_UPLOAD_FILE_SUCCESS';
export const CLIENT_IPFS_STORAGE_UPLOAD_FILE_FAILURE = 'CLIENT_IPFS_STORAGE_UPLOAD_FILE_FAILURE';

export const CLIENT_IPFS_STORAGE_DOWNLOAD_FILE = 'CLIENT_IPFS_STORAGE_DOWNLOAD_FILE';
export const CLIENT_IPFS_STORAGE_DOWNLOAD_FILE_SUCCESS = 'CLIENT_IPFS_STORAGE_DOWNLOAD_FILE_SUCCESS';
export const CLIENT_IPFS_STORAGE_DOWNLOAD_FILE_FAILURE = 'CLIENT_IPFS_STORAGE_DOWNLOAD_FILE_FAILURE';

export const CLIENT_IPFS_STORAGE_UPLOAD_FILE_STATUS = 'CLIENT_IPFS_STORAGE_UPLOAD_FILE_STATUS';
export const CLIENT_IPFS_STORAGE_DOWNLOAD_FILE_STATUS = 'CLIENT_IPFS_STORAGE_DOWNLOAD_FILE_STATUS';

export const CLIENT_UPLOADED_LIST_FILE_ADD = 'CLIENT_UPLOADED_LIST_FILE_ADD';
export const CLIENT_UPLOADED_LIST_DELETE_ALL = 'CLIENT_UPLOADED_LIST_DELETE_ALL';

export const CLIENT_UPLOADS_LIST_ENTRY_ADD = 'CLIENT_UPLOADS_LIST_ENTRY_ADD';
export const CLIENT_UPLOADS_LIST_ENTRY_UPDATE_PROGRESS = 'CLIENT_UPLOADS_LIST_ENTRY_UPDATE_PROGRESS';
export const CLIENT_UPLOADS_LIST_ENTRY_SET_ERROR = 'CLIENT_UPLOADS_LIST_ENTRY_SET_ERROR';
export const CLIENT_UPLOADS_LIST_ENTRY_DELETE = 'CLIENT_UPLOADS_LIST_ENTRY_DELETE';
export const CLIENT_UPLOADS_LIST_ENTRY_DELETE_ALL = 'CLIENT_UPLOADS_LIST_ENTRY_DELETE_ALL';

export const CLIENT_DOWNLOAD_LIST_ENTRY_ADD = 'CLIENT_DOWNLOAD_LIST_ENTRY_ADD';
export const CLIENT_DOWNLOAD_LIST_ENTRY_SET_ERROR = 'CLIENT_DOWNLOAD_LIST_ENTRY_SET_ERROR';
export const CLIENT_DOWNLOAD_LIST_ENTRY_DELETE = 'CLIENT_DOWNLOAD_LIST_ENTRY_DELETE';
export const CLIENT_DOWNLOAD_LIST_ENTRY_DELETE_ALL = 'CLIENT_DOWNLOAD_LIST_ENTRY_DELETE_ALL';

export const CLIENT_DOWNLOADED_LIST_ENTRY_ADD = 'CLIENT_DOWNLOADED_LIST_ENTRY_ADD';
export const CLIENT_DOWNLOADED_LIST_DELETE_ALL = 'CLIENT_DOWNLOADED_LIST_DELETE_ALL';

export const CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE = 'CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE';
export const CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE_SUCCESS = 'CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE_SUCCESS';
export const CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE_FAILURE = 'CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE_FAILURE';
export const CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE_STATUS = 'CLIENT_DAPP_IPFS_STORAGE_UPLOAD_FILE_STATUS';
