// OrbitDB
export const ORBIT_DB_CREATE_DATABASE = 'ORBIT_DB_CREATE_DATABASE';
export const ORBIT_DB_CREATE_DATABASE_SUCCESS = 'ORBIT_DB_CREATE_DATABASE_SUCCESS';
export const ORBIT_DB_CREATE_DATABASE_FAILURE = 'ORBIT_DB_CREATE_DATABASE_FAILURE';

export const ORBIT_DB_OPEN_DATABASE = 'ORBIT_DB_OPEN_DATABASE';
export const ORBIT_DB_OPEN_DATABASE_SUCCESS = 'ORBIT_DB_OPEN_DATABASE_SUCCESS';
export const ORBIT_DB_OPEN_DATABASE_FAILURE = 'ORBIT_DB_OPEN_DATABASE_FAILURE';

export const ORBIT_DB_ADD_ENTRY = 'ORBIT_DB_ADD_ENTRY';
export const ORBIT_DB_ADD_ENTRY_SUCCESS = 'ORBIT_DB_ADD_ENTRY_SUCCESS';
export const ORBIT_DB_ADD_ENTRY_FAILURE = 'ORBIT_DB_ADD_ENTRY_FAILURE';

export const ORBIT_DB_GET_ENTRY = 'ORBIT_DB_GET_ENTRY';
export const ORBIT_DB_GET_ENTRY_SUCCESS = 'ORBIT_DB_GET_ENTRY_SUCCESS';
export const ORBIT_DB_GET_ENTRY_FAILURE = 'ORBIT_DB_GET_ENTRY_FAILURE';

export const ORBIT_DB_GET_ALL_ENTRIES = 'ORBIT_DB_GET_ALL_ENTRIES';
export const ORBIT_DB_GET_ALL_ENTRIES_SUCCESS = 'ORBIT_DB_GET_ALL_ENTRIES_SUCCESS';
export const ORBIT_DB_GET_ALL_ENTRIES_FAILURE = 'ORBIT_DB_GET_ALL_ENTRIES_FAILURE';
