// This application opens links that start with this protocol
export const HTTP_PROTOCOL_PREFIX = 'arr';
export const HTTP_PROTOCOL = `${HTTP_PROTOCOL_PREFIX}://`;

export const HTTP_PROTOCOL_OPEN_LINK = 'HTTP_PROTOCOL_OPEN_LINK';
export const HTTP_PROTOCOL_OPEN_LINK_SUCCESS = 'HTTP_PROTOCOL_OPEN_LINK_SUCCESS';
export const HTTP_PROTOCOL_OPEN_LINK_FAILURE = 'HTTP_PROTOCOL_OPEN_LINK_FAILURE';
export const HTTP_PROTOCOL_OPEN_DAPP = 'HTTP_PROTOCOL_OPEN_DAPP';
