export const CLIENT_CLEAR_NOTIFICATION = 'CLIENT_CLEAR_NOTIFICATION';
export const CLIENT_CLEAR_ALL_NOTIFICATIONS = 'CLIENT_CLEAR_ALL_NOTIFICATIONS';
export const CLIENT_ADD_NOTIFICATION = 'CLIENT_ADD_NOTIFICATION';
export const CLIENT_NOTIFICATION_TRIGGER_ACTION = 'CLIENT_NOTIFICATION_TRIGGER_ACTION';
export const TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL';
