import * as path from 'path';
import { isDev } from '../../helpers/constants/globalVariables';

export const DAPP_SET_FOCUS = 'DAPP_SET_FOCUS';
export const DAPP_RESET_FOCUS = 'DAPP_RESET_FOCUS';
export const DAPP_CONTENT_LOADED = 'DAPP_CONTENT_LOADED';

export const ON_DAPP_INSTALL = 'ON_DAPP_INSTALL';
export const ON_DAPP_INSTALL_SUCCESS = 'ON_DAPP_INSTALL_SUCCESS';
export const ON_DAPP_INSTALL_FAILURE = 'ON_DAPP_INSTALL_FAILURE';
export const ON_DAPP_CLOSE = 'ON_DAPP_CLOSE';

export const DAPP_DOWNLOAD = 'DAPP_DOWNLOAD';
export const DAPP_DOWNLOAD_SUCCESS = 'DAPP_DOWNLOAD_SUCCESS';
export const DAPP_DOWNLOAD_FAILURE = 'DAPP_DOWNLOAD_FAILURE';
export const GET_ALL_DAPPS = 'GET_ALL_DAPPS';
export const GET_ALL_DAPPS_SUCCESS = 'GET_ALL_DAPPS_SUCCESS';
export const GET_ALL_DAPPS_FAILURE = 'GET_ALL_DAPPS_FAILURE';

export const UPDATE_INSTALLED_DAPPS = 'UPDATE_INSTALLED_DAPPS';

export const REMOVE_TRAY_ITEM = 'REMOVE_TRAY_ITEM';
