// Component
export const IPFS_ROOM_SUBSCRIBE = 'IPFS_ROOM_SUBSCRIBE';
export const IPFS_ROOM_SUBSCRIBE_SUCCESS = 'IPFS_ROOM_SUBSCRIBE_SUCCESS';
export const IPFS_ROOM_SUBSCRIBE_FAILURE = 'IPFS_ROOM_SUBSCRIBE_FAILURE';

export const IPFS_ROOM_SEND_MESSAGE_BROADCAST = 'IPFS_ROOM_SEND_MESSAGE_BROADCAST';
export const IPFS_ROOM_SEND_MESSAGE_BROADCAST_SUCCESS = 'IPFS_ROOM_SEND_MESSAGE_BROADCAST_SUCCESS';
export const IPFS_ROOM_SEND_MESSAGE_BROADCAST_FAILURE = 'IPFS_ROOM_SEND_MESSAGE_BROADCAST_FAILURE';

export const IPFS_ROOM_SEND_MESSAGE_TO_PEER = 'IPFS_ROOM_SEND_MESSAGE_TO_PEER';
export const IPFS_ROOM_SEND_MESSAGE_TO_PEER_SUCCESS = 'IPFS_ROOM_SEND_MESSAGE_TO_PEER_SUCCESS';
export const IPFS_ROOM_SEND_MESSAGE_TO_PEER_FAILURE = 'IPFS_ROOM_SEND_MESSAGE_TO_PEER_FAILURE';

export const IPFS_ROOM_SEND_MESSAGE_TO_DAPP = 'IPFS_ROOM_SEND_MESSAGE_TO_DAPP';

export const IPFS_ROOM_PEER_JOINED = 'IPFS_ROOM_PEER_JOINED';
export const IPFS_ROOM_PEER_LEFT = 'IPFS_ROOM_PEER_LEFT';

export const IPFS_ROOM_LEAVE = 'IPFS_ROOM_LEAVE';
export const IPFS_ROOM_LEAVE_SUCCESS = 'IPFS_ROOM_LEAVE_SUCCESS';
export const IPFS_ROOM_LEAVE_FAILURE = 'IPFS_ROOM_LEAVE_FAILURE';

export const IPFS_ROOM_GET_PEERS = 'IPFS_ROOM_GET_PEERS';
export const IPFS_ROOM_GET_PEERS_SUCCESS = 'IPFS_ROOM_GET_PEERS_SUCCESS';
export const IPFS_ROOM_GET_PEERS_FAILURE = 'IPFS_ROOM_GET_PEERS_FAILURE';
