export const SET_ROOM_NAME = 'SET_ROOM_NAME';
export const RESET_ROOM_NAME = 'RESET_ROOM_NAME';

export const MAIN_PAGE_FORM = 'MAIN_PAGE_FORM';
export const CHAT_PAGE_MESSAGE_FORM = 'CHAT_PAGE_MESSAGE_FORM';
