const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
const TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL';
const TOGGLE_LOADER_PANEL = 'TOGGLE_LOADER_PANEL';
const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
const CLEAR_ALL_NOTIFICATIONS = 'CLEAR_ALL_NOTIFICATIONS';
const TOGGLE_STATUS_BAR_PANEL = 'TOGGLE_STATUS_BAR_PANEL';
const APPS_FEED_RESIZE = 'APPS_FEED_RESIZE';
const ADD_APP_ITEM = 'ADD_APP_ITEM';
const SWITCH_DAPP = 'SWITCH_DAPP';
const TOGGLE_HOME = 'TOGGLE_HOME';
const TOGGLE_APP_HOME = 'TOGGLE_APP_HOME';

// Dapp communication protocol
const INTENT_OPEN_CHANNELS = 'INTENT_OPEN_CHANNELS';
const OPEN_CHANNEL = 'OPEN_CHANNEL';
const OPEN_CHANNEL_SUCCESS = 'OPEN_CHANNEL_SUCCESS';
const BIND_OPEN_CHANNELS_DONE = 'BIND_OPEN_CHANNELS_DONE';

// Component-channel resolver
const INTENT_CHANNEL_DATA_PASS = 'INTENT_CHANNEL_DATA_PASS';
const ACCEPT_CHANNEL_DATA_PASS = 'ACCEPT_CHANNEL_DATA_PASS';

export {
  INCREMENT_COUNTER,
  DECREMENT_COUNTER,
  TOGGLE_NOTIFICATION_PANEL,
  TOGGLE_LOADER_PANEL,
  CLEAR_NOTIFICATION,
  CLEAR_ALL_NOTIFICATIONS,
  TOGGLE_STATUS_BAR_PANEL,
  APPS_FEED_RESIZE,
  ADD_APP_ITEM,
  SWITCH_DAPP,
  TOGGLE_HOME,
  TOGGLE_APP_HOME,

  INTENT_OPEN_CHANNELS,
  OPEN_CHANNEL,
  OPEN_CHANNEL_SUCCESS,
  BIND_OPEN_CHANNELS_DONE,
  INTENT_CHANNEL_DATA_PASS,
  ACCEPT_CHANNEL_DATA_PASS
}
