
export const TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL';
export const TOGGLE_LOADER_PANEL = 'TOGGLE_LOADER_PANEL';
export const TOGGLE_SETTINGS_PANEL = 'TOGGLE_SETTINGS_PANEL';
export const TOGGLE_SEARCH_PANEL = 'TOGGLE_SEARCH_PANEL';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const CLEAR_ALL_NOTIFICATIONS = 'CLEAR_ALL_NOTIFICATIONS';
export const TOGGLE_STATUS_BAR_PANEL = 'TOGGLE_STATUS_BAR_PANEL';
export const LOGGER_WRITE = 'LOGGER_WRITE';
export const LOGGER_WRITE_SUCCESS = 'LOGGER_WRITE_SUCCESS';
export const LOGGER_WRITE_FAILURE = 'LOGGER_WRITE_FAILURE';
export const TOGGLE_PEERS_BAR_PANEL = 'TOGGLE_PEERS_BAR_PANEL';
export const APPS_FEED_RESIZE = 'APPS_FEED_RESIZE';
export const ADD_APP_ITEM = 'ADD_APP_ITEM';
export const SWITCH_DAPP = 'SWITCH_DAPP';
export const TOGGLE_HOME = 'TOGGLE_HOME';
 
export const TOGGLE_APP_HOME = 'TOGGLE_APP_HOME';

// Dapp communication protocol
export const INTENT_OPEN_CHANNELS = 'INTENT_OPEN_CHANNELS';
export const OPEN_CHANNEL = 'OPEN_CHANNEL';
export const OPEN_CHANNEL_SUCCESS = 'OPEN_CHANNEL_SUCCESS';
export const BIND_OPEN_CHANNELS_DONE = 'BIND_OPEN_CHANNELS_DONE';

// Component-channel resolver
export const INTENT_CHANNEL_DATA_PASS = 'INTENT_CHANNEL_DATA_PASS';
export const ACCEPT_CHANNEL_DATA_PASS = 'ACCEPT_CHANNEL_DATA_PASS';

export const SET_TRAY_PROGRESS = "SET_TRAY_PROGRESS"; 
export const SET_TRAY_COUNTER = "SET_TRAY_COUNTER";
export const REMOVE_TRAY_ITEM = "REMOVE_TRAY_ITEM";


